url_list = [
            "https://www.overcomingbias.com/archive", #temp
            "https://www.greaterwrong.com/?sort=hot",
            "https://www.greaterwrong.com/?sort=new",
            "https://www.lesswrong.com/allPosts",
            "https://www.alignmentforum.org/",
            "https://forum.effectivealtruism.org/",
            "https://www.lesswrong.com/",
            "https://forum.effectivealtruism.org/allPosts",
            "https://forum.obsidian.md/c/knowledge-management/6",
            ##
            "https://pattern.swarma.org/articles",
            "https://pattern.swarma.org/learn_paths",
            "https://pattern.swarma.org/wechat_articles",
            "https://swarma.org/",
            "https://shimo.im/docs/tjRWrtPYp8JTrpHY/read", # no longer publicly accessible # resumed
            # "https://acacess.substack.com/archive?sort=new",
            "https://letters.acacess.com/page/2/",
            "https://rizime.substack.com/archive?sort=new",
            "http://headsalon.org/feed", # 
            "https://www.foretold.io/c/home/activity",
            "https://www.overcomingbias.com/",
            "https://intelligence.org/all-posts/",
            # "https://www.allnow.com/",
            # "https://www.weixinso.com/home/index/profile/bid/3894463207.html", # no update

            "https://bookdown.org/home/archive/",
            # "https://sniggle.net/TPL/index5.php?entry=annotated",
            "https://sinceriously.fyi/", #
            "https://deconstructingyourself.com/all-articles", #
            "https://slatestarscratchpad.tumblr.com/archive", 
            "https://conge.github.io/archive/",
            "https://reader.one/",            
            "https://astralcodexten.substack.com/archive?sort=new",
            # "http://openmindclub.blog.caixin.com/", # No longer updated
            "https://theangelphilosopher.com/",
            "https://alistapart.com/articles/",
            "https://zhaoolee.com/garss/",
            "https://daimajia.com/following",
            "https://maoruimas.github.io/zxcs/",
            "http://headsalon.org/catalog",
            "https://diff.blog/",
            "https://revisesociology.com/",
            "https://www.metafilter.com",
            "https://theanarchistlibrary.org/special/index",
            "https://zoomquiet.substack.com/",
            "https://slimemoldtimemold.com/",
            "https://onehu.xyz/categories",
            "https://www.zhihuban.ml/2021/12/navigation.html",
            "https://deathisbadblog.com/",
#             "https://booka.openmindcloud.com/SUMMARY.html", # 404
#             "https://www.leeds.ac.uk/rss/news",
            "https://writingchinese.leeds.ac.uk/book-reviews/",
            "https://writingchinese.leeds.ac.uk/book-club/",
            "https://rssnewshub.com/",
            "https://rssnewshub.com/feed/latest",
            # "https://from-ai-to-zombies.eu/files.html", #temp
            # "https://www.readthesequences.com/Contents",#temp
            # "https://liqi.io/posts/", #temp
            "https://www.cnfeat.com/archive/",
            "http://newsletter.hardwaylab.com/",
            "https://jlcollinsnh.com/",
            "https://www.madfientist.com/articles/",
            "https://www.mrmoneymustache.com/",
            "http://earlyretirementextreme.com/",
            "https://hub.baai.ac.cn/",
            "https://www.yuque.com/hardwaylab/book",
            "https://www.yuque.com/hardwaylab/cardstyle",
            "https://www.yuque.com/hardwaylab/qve8ct",
            "https://www.yuque.com/hardwaylab/paulgraham", 
            "https://www.yuque.com/hardwaylab/smn5fc", 
            "https://www.yuque.com/hardwaylab/wgolop",
#             "http://shaderstore.cn/archive/",
            "https://www.less-bug.com/archives/",
            "https://shao.fun/blog/",
            "https://moyu.work/news",
            "https://blog.misaka.rest/",
            "https://xiaobot.netlify.app/",
            "http://anotherdayu.com/?feed=rss",
            "https://sharegpt.com/",
            "https://42share.io/",
            "https://einverne.github.io/archive.html",
            "https://muspimerol.site/blog",
            "https://www.ml-quant.com/",
]
