# This is a basic workflow to help you get started with Actions

name: saving

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "0 0/4 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
    
    # - name: apt installs
    #   run: |
    #       sudo apt-get update && sudo apt install chromium-chromedriver=1:85.0.4183.83-0ubuntu0.20.04.2  -y
    
    - name: Setup & Check enviroment
      run: |
        pwd
        python --version
        pip install -U requests
        # pip install -U requests selenium
        # which chromium-browser
        
    # Runs a single command using the runners shell
    - name: Run
      env:
        EMAIL_ADD: ${{ secrets.EMAIL_ADD }}
        PASSD: ${{ secrets.PASSD }}
        MYACCESSKEY: ${{ secrets.MYACCESSKEY }}
        MYSECRET: ${{ secrets.MYSECRET }}
      run: python use_api.py
